# Site settings
title: Burnian's Blog
description: Burnian Zhou's Personal Blog Site
url: "https://burnian.github.io"  # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
# permalink: /:categories/:title/
language: true # true for Chinese, false for English


# User settings
user_name: Burnian Zhou
user_desc: I'm a nomad Indie Game Developer, always searching for the next challenge and beauty of idea.
user_title: Indie Game Developer
email: burnian@qq.com
qq: 791829698
wechat: burnian
jekyll: https://jekyllrb.com
github: https://github.com/burnian
# Publish posts or collection documents with a future date.
future: false


# markdown settings
# 现在不需要设置markdown的渲染方式了，因为jekyll 3.0以上版本默认使用
# kramdown来渲染markdown并使用rouge来高亮代码，我们需要做的只是修改css
# document: http://jekyllrb.com/docs/configuration/#kramdown
# markdown: kramdown
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important
#   syntax_highlighter_opts:
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1


# Build settings
# markdown text formats
indent: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"

# comment plugin
gitalk:
  enable: true

paginate: 5
paginate_paths: ["pages/:num", "pages/fiction/:num", "pages/travel/:num", "pages/life/:num", "pages/technology/:num", "pages/tutorial/:num"]

# collections:
#   posts:
#     output: true # 只有posts的output默认是true的，其他collection文件夹不是

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_posts/fiction"
    values:
      categories: "fiction"
  - scope:
      path: "_posts/travel"
    values:
      categories: "travel"
  - scope:
      path: "_posts/life"
    values:
      categories: "life"
  - scope:
      path: "_posts/technology"
    values:
      categories: "technology"
  - scope:
      path: "_posts/tutorial"
    values:
      categories: "tutorial"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Baidu Analytics
baidu:
  enable: true

# Google Analytics
# ga_track_id: 'UA-134814157-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto

# MathJax rendering for layout:page, used to render math fomula.
page-mathjax: false


# friend's link
friends: [
  {
    title: "白衣渡江",
    href: "https://blog.whiterobe.top"
  }
]
